name: newdapoer
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: '>=3.0.2 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.5
  material_design_icons_flutter: ^6.0.7096
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/icon/icon1.png"
flutter:
  uses-material-design: true
  assets:
    - assets/icon/
    - assets/font/
    - assets/file/
    - assets/image/
    - assets/icon/icon1.png